"""add is_active to service

Revision ID: 14f202ba4ecf
Revises: 8850cafb113e
Create Date: 2026-09-30 09:39:26.312825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14f202ba4ecf'
down_revision: Union[str, Sequence[str], None] = '8850cafb113e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 既有 service 資料沒有 is_active 欄位，backfill 為 True（啟用），
    # 確保現有服務（cut/perm/color/care）升級後維持可預約狀態。
    op.add_column(
        'service',
        sa.Column(
            'is_active',
            sa.Boolean(),
            nullable=False,
            server_default=sa.true(),
        ),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('service', 'is_active')
    # ### end Alembic commands ###
