"""add line user id to booking

Revision ID: 3293267d8dcc
Revises: 57a3da795200
Create Date: 2026-09-20 15:48:02.051066

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3293267d8dcc'
down_revision: Union[str, Sequence[str], None] = '57a3da795200'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('line_user_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_booking_line_user_id'), 'booking', ['line_user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_booking_line_user_id'), table_name='booking')
    op.drop_column('booking', 'line_user_id')
    # ### end Alembic commands ###
