"""add is_active to staff

Revision ID: b8507c17d612
Revises: 14f202ba4ecf
Create Date: 2026-09-30 11:30:55.537694

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8507c17d612'
down_revision: Union[str, Sequence[str], None] = '14f202ba4ecf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 既有 staff 資料（Andy）沒有 is_active 欄位，backfill 為 True
    # （啟用），確保升級後既有設計師維持可預約狀態。
    op.add_column(
        'staff',
        sa.Column(
            'is_active',
            sa.Boolean(),
            nullable=False,
            server_default=sa.true(),
        ),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('staff', 'is_active')
    # ### end Alembic commands ###
