"""add reminder sent at to booking

Revision ID: cc50fbe549d1
Revises: 3293267d8dcc
Create Date: 2026-09-20 17:09:55.521453

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc50fbe549d1'
down_revision: Union[str, Sequence[str], None] = '3293267d8dcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('booking', sa.Column('reminder_sent_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('booking', 'reminder_sent_at')
    # ### end Alembic commands ###
